victorskl/yawsso

README.md, setup.py, tests/test_cli.py, yawsso/__init__.py, yawsso/cli.py
* Bump version 0.2.0
* Added more unit test cases
* Polished up code a bit
* Updated README
=> Added optional flag for aws binary location

.github/workflows/prbuild.yml, .gitignore, Makefile, README.md
* Trying codecov.io for coverage report
* Added Makefile
=> Added code coverage report

.gitignore, README.md, tests/__init__.py, tests/test_cli.py, yawsso/__init__.py, yawsso/__main__.py, yawsso/cli.py
* Release 0.3.0
* Improved multi named profiles sync logic
* Added default profile sync with dedicated flag
* Added unit tests for full code coverage
* Minor refactor
=> Improved multi profiles sync

tests/test_cli.py, yawsso/cli.py
* Should fetch credentials with assume-role
when role-arn avail. And just need to check
source profile has valid SSO login session.
* Follow how aws cli done with source profile
and sts:AssumeRole explain here:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html
=> Fixed source profile impl

.gitignore, Makefile, README.md, main.tf, tests/__init__.py, tests/test_cli.py, yawsso/__init__.py, yawsso/cli.py
* Added subcommand login
* Added eager sync source profile logic
* Added TRACE log level
* Silent and UNIX friendly logging by default
* Improved export var logic flow
* Minor refactor
=> Release 0.4.0rc2

.coveragerc, .gitignore, .travis.yml, Makefile, README.md, pytest.ini, setup.py, tests/__init__.py, tests/test_cli.py, tox.ini, yawsso/__init__.py, yawsso/cli.py
* Fixed role chaining assume role duration limit to 3600 seconds
* Improved '-e' option on either side of login command
* Added travis, tox, coveralls for trying out alt test setup
* Minor refactor
=> Release 0.4.0rc3

Makefile, README.md, tests/test_cli.py, yawsso/__init__.py, yawsso/cli.py
* Bump dev version
* Updated README and Makefile
=> Added support reading cred and config file from CLI env vars

README.md, tests/test_cli.py, yawsso/__init__.py, yawsso/cli.py
=> Added support profile prefix pattern

.codacy.yml, .github/workflows/prbuild.yml, .travis.yml, README.md, requirements.txt, setup.py, tests/test_cli.py, yawsso/__init__.py, yawsso/__main__.py, yawsso/cli.py
* Bump version 0.6.0rc1
* Improved pyperclip import logic and added test cases
* Fix #26 - create AWS_SHARED_CREDENTIALS_FILE if not exists
* Fix #27 - Python version requirement check
* Added codacy config
* Improved README
=> Release 0.6.0rc1

.github/workflows/prbuild.yml, .travis.yml, Makefile, README.md, setup.py, yawsso/__init__.py, yawsso/cli.py
- Fixed login named profile then export token
- Fixed to pin pyperclip 1.7.0 for Travis CI test
=> fix login export

.github/workflows/prbuild.yml, tests/test_cli.py, yawsso/cli.py
* Fix #33 - Tildes aren't being expanded on file paths
* Replaced master with main branch
=> Added support expand user path

.codacy.yml, README.md, tests/test_cli.py, yawsso/__init__.py, yawsso/cli.py
* Keep up according to Codacy report
* Added more badges, fun!
=> Improved code

yawsso/__init__.py
* Applied suggestion in PR #46
* Bumped patch version `0.6.2`
=> Release 0.6.2

tests/test_cli.py, yawsso/cli.py
Implements basic rename functionality for issue #50
Not a python developer so input is welcome! Still todo, add support for login command.
=> Implement profile rename functionality

README.md, tests/test_cli.py, yawsso/cli.py
=> Add rename functionality to login subcommand

tests/test_cli.py, yawsso/cli.py
* Removed same region enforcing check which may be
too restrictive for cross region use case
* Fixed test and follow up of #61
=> Allow cross region

Makefile, README.md, tests/test_cli.py, yawsso/cli.py
=> Added Base64 encoded clipboard masking

.gitignore, Makefile, README.md, h.py, setup.py, tests/test_cli.py, tests/test_utils.py, yawsso/__init__.py, yawsso/utils.py
* Feature request #57
* Bumped version 1.0.0rc2
* Improved cli unit tests on Windows
=> Added support for cred export as Windows environment variables

.codeclimate.yml, README.md, h.py, tests/test_cli.py, tests/test_cmd.py, yawsso/__init__.py, yawsso/cli.py, yawsso/cmd.py
* Bumped version `1.0.0rc3`
* Minor refactor to cater auto subcommand addition
* Related #60
=> Added auto subcommand use case

tests/test_utils.py, yawsso/__init__.py, yawsso/utils.py
=> Fixed export env var under Windows MINGW64 Git Bash condition

tests/test_cli.py, yawsso/core.py
=> Disabled region value copying over to credentials file

tests/test_cli.py, yawsso/cli.py, yawsso/core.py
=> Added region flag to control setting the region in the cred file
